name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Coolify
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # if: github.event.workflow_run.conclusion == 'success'
    if: github.head_ref == 'feat/migate-to-coolify'

    concurrency:
      group: coolify-production
      cancel-in-progress: false

    steps:
      - name: Trigger Coolify deployment
        env:
          COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: 'curl --fail-with-body --retry 3 --request POST --header "Authorization: Bearer ${COOLIFY_TOKEN}" "${COOLIFY_WEBHOOK}"'
